-- if true then return {} end -- WARN: REMOVE THIS LINE TO ACTIVATE THIS FILE

-- Customize Mason

---@type LazySpec
return {
  -- use mason-tool-installer for automatically installing Mason packages
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    -- overrides `require("mason-tool-installer").setup(...)`
    opts = {
      -- Make sure to use the names found in `:Mason`
      ensure_installed = {
        "arduino-language-server",
        "pylint",
        "pyright",
        "cspell",
        "stylelint",
        "sql-formatter",
        "google-java-format",
        "tree-sitter-cli",
        "autopep8",
        "bash-debug-adapter",
        "bash-language-server",
        "beautysh",
        "cmake-language-server",
        "cmakelang",
        "cmakelint",
        "commitlint",
        "cpplint",
        "cpptools",
        "css-lsp",
        "debugpy",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "eslint-lsp",
        "eslint_d",
        "gdtoolkit",
        "go-debug-adapter",
        "golines",
        "gopls",
        "gotests",
        "gradle-language-server",
        "grammarly-languageserver",
        "html-lsp",
        "htmlhint",
        "java-debug-adapter",
        "jq",
        "jq-lsp",
        "js-debug-adapter",
        "json-lsp",
        "jsonlint",
        "luacheck",
        "markdownlint",
        "prettierd",
        "python-lsp-server",
        "shellcheck",
        "stylelint-lsp",
        "textlint",
        "typescript-language-server",
        "vim-language-server",
        "vscode-java-decompiler",
        "vue-language-server",
        "xmlformatter",
        "yaml-language-server",
        "yamlfmt",
      },
      automatic_installation = false,
      automatic_setup = true,
    },
  },
}
